device: "auto"
train: []
inference:
  - _target_: src.metrics.Accuracy
    name: "accuracy"
  - _target_: src.metrics.Precision
    name: "precision"
  - _target_: src.metrics.Recall
    name: "recall"
  - _target_: src.metrics.F1
    name: "f1"
